name: pub_crap_checker
description: Pub Crap Checker
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'
  flutter: '>=3.1.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Routing
  go_router: ^3.1.0

  # Models and annotation
  meta: any
  json_annotation: any
  freezed_annotation: ^2.0.1

  # Database
  shared_preferences: ^2.0.13

  # BLoC
  stream_bloc: ^0.4.0

  # Utility
  l: ^3.2.0
  intl: ^0.17.0
  url_launcher: ^6.1.0
  platform_info: ^3.2.0

  # Firebase
  #firebase: ^9.0.2
  #firebase_core: ^1.16.0
  #firebase_analytics: ^9.1.7
  #firebase_auth: ^3.3.17
  #firebase_remote_config: ^2.0.8
  #cloud_firestore: ^3.1.14
  #firebase_storage: ^10.2.17
  #firebase_performance: ^0.8.0+13
  #flutterfire_ui: ^0.4.0+5

  # Inversion of control
  get_it: ^7.2.0
  injectable: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: any
  build_web_compilers: ^3.2.1
  build_runner: ^2.1.10
  grinder: ^0.9.1
  path: ^1.8.1
  go_router_builder: ^1.0.3
  freezed: ^2.0.2
  icons_launcher: ^1.1.3
  flutter_native_splash: ^2.0.1+1
  pubspec_generator: ^3.0.1
  flutter_gen_runner: ^4.0.1
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true

# Flutter assets codegen
flutter_gen:
  output: lib/src/common/constant/
  line_length: 120